### PR TITLE
Fix setting undefined value in the store

### PR DESCRIPTION
**Pull request by conqeror**
Removing value should be performed using store.delete
See here: https://github.com/sindresorhus/conf/blob/master/source/index.ts#L193

### CODE REVIEW

**Comment by qwhex** [comment]
Looks good, but where do we delete values from the store?
What was the bug that warranted this fix?

**Comment by conqeror** [comment]
@qwhex 
Well, not sure where exactly does it happen, but we've got this report from the latest develop (and it renders app unusable):
image

**Comment by conqeror** [comment]
```
export interface TxHistoryStoreData {
  txHistory: Record<NetworkName, StoredHistory.StoredHistory | undefined>
}
```
But this seems to be the only place where we can have `undefined` in the store.

**Comment by qwhex** [comment]
I think the root of the problem is that the migration is missing for WalletData (which adds this new store item).
The default seems to be `{}` (check `defaultTxHistoryStoreData`), so I'm not sure why `undefined` is an option here.

So I'd add a migration, but also leave this fix in.

**Review by qwhex — APPROVED** [review]

**Pull request merged**
