### PR TITLE
[ETCM-353] Terms & Conditions

### PR DESCRIPTION
**Pull request by qwhex**
Keep this as the last merged PR and I'll update storyshots for you.

### CODE REVIEW

**Comment by conqeror** [comment]
image
This is how it looks on the lowest resolution, not sure if we can somehow fit it more nicely.

NIT: I would maybe move static T&C (that formatted text) to the separate file so that we can keep actual component leaner (and not have to scroll through 300 lines of static content).

Maybe it makes more sense to have checkbox at the end of T&C to make sure user at least scrolled though them (not that it makes difference :D)

Do we want user to accept T&C every time when adding new wallet? (isn't once enough?)

**Comment by qwhex** [comment]
Good points! 

> This is how it looks on the lowest resolution, not sure if we can somehow fit it more nicely.

It was fine for me on Linux :thinking: The big margin at the top looks suspect. Will try on my Mac and fix it.

> NIT: I would maybe move static T&C (that formatted text) to the separate file so that we can keep actual component leaner (and not have to scroll through 300 lines of static content).

At first I made it a separate html file and tried to import it without success. After looking into it, it doesn't worth the effort IMHO.
I'll move it to a separate tsx file though.

> Maybe it makes more sense to have checkbox at the end of T&C to make sure user at least scrolled though them (not that it makes difference :D)

Yeah, it's there if someone wants to read it (and they should if they accept it).
It's not our responsibility to enforce that they actually do.

> Do we want user to accept T&C every time when adding new wallet? (isn't once enough?)

I think it doesn't matter, especially that wallet creation won't be a frequent action without multiple wallet support.

**Review by conqeror — APPROVED** [review]
:shipit:

**Review by kapke — APPROVED** [review]
LGTM!

**Pull request merged**
